version: 2
updates:
  # Updates for Github Actions used in the repo
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  # Updates for Gradle dependencies used in the app
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      ignore:
        - dependency-name: org.springframework.boot:spring-boot-starter-test
        - dependency-name: org.springframework.boot:spring-boot-starter-web
        - dependency-name: org.springframework.boot:spring-boot-starter-security
        - dependency-name: org.springframework.boot:spring-boot-starter-data-jpa
